---
- name: Create cluster-admin role binding
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: skylar-cluster-admin
      subjects:
          - kind: User
            name: skylar
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin

- name: Create htpasswd Secret
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: default-htpasswd
        namespace: openshift-config
      data:
        htpasswd: "{{ htpasswd_contents | b64encode}}"
      type: Opaque

- name: Patch cluster OAuth
  kubernetes.core.k8s_json_patch:
    kind: OAuth
    api_version: config.openshift.io/v1
    name: cluster
    patch:
      - op: add
        path: /spec
        value:
          identityProviders:
            - htpasswd:
                fileData:
                  name: default-htpasswd
              mappingMethod: claim
              name: skylar-htpasswd
              type: HTPasswd
...